sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/MyCppGame.Classes -R /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/Classes/
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.2d /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/2d/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.3d /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/3d/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.audio.linux /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/audio/linux/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.audio /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/audio/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.base /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/base/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.deprecated /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/deprecated/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.math /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/math/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.navmesh /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/navmesh/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.network /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/network/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.physics /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/physics/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.physics3d /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/physics3d/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.platform /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/platform/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.platform.desktop /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/platform/desktop/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.platform.linux /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/platform/linux/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.renderer /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/renderer/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.storage.local-storage /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/storage/local-storage/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.ui /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/ui/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.ui.UIEditBox /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/ui/UIEditBox/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.editor-support.cocosbuilder /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/editor-support/cocosbuilder/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.editor-support.cocostudio /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/editor-support/cocostudio/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.editor-support.cocostudio.ActionTimeline /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/editor-support/cocostudio/ActionTimeline/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.editor-support.cocostudio.WidgetReader /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/editor-support/cocostudio/WidgetReader/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/cocos2d.cocos.editor-support.spine /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/cocos2d/cocos/editor-support/spine/*
sudo ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v  --fields=+l -f ~/.vim/MyCppGame.libkbeclient -R /home/ypf/workspace/cocos2dx/cocos2d-x-3.11-project/MyCppGame/libKBEClient/
